### ISSUE TITLE
I have an issue with OCSAgent and OCSServer

### ISSUE THREAD

**Issue by johnsaenz83** [OCSInventory-NG/UnixAgent#389] opened 2022-01-10 19:12 UTC
### General informations
Operating system :  Red Hat 6.6 and Red hat 6.10
Perl version : perl and perl5

### OCS Inventory informations
Unix agent version :  OCS-NG_unified_unix_agent_v2.8.1

### Problem's description
I have installed an OCS agent on the red hat linux server, but it does not report me on my server and I found the following message in the log. 

### Inventory log file ( optional )
[Wed Jan 05 23:45:36.974223 2022] [perl:error] [pid 885] [client 10.69.60.149:51891] 
\nnot well-formed (invalid token) at line 11221, column 20, byte 402619 at /usr/lib64/perl5/vendor_perl/XML/Parser.pm line 187.\n
10.69.60.149 - - [05/Jan/2022:23:45:36 +0100] "POST /ocsinventory HTTP/1.1" 500 527 "-" "OCS-NG_unified_unix_agent_v2.8.1"

**Comment by wiltonsr** [comment] 2022-01-19 15:05
Duplicate of #275

**Comment by Lea9250** [comment] 2022-12-23 14:30
Hi @johnsaenz83,

A fix was provided and the issue should no longer be present in latest versions of the agent. Try updating your agent and see if it persists. 
I'll close the issue now but feel free to re open if needed.

Regards,
Léa

**Closed by Lea9250** 2022-12-23 14:30 UTC
