### ISSUE TITLE
Change broke my setup: ssl = 0 is NOT respected #336

### ISSUE THREAD

**Issue by Sloth-on-meth** [OCSInventory-NG/UnixAgent#414] opened 2022-07-21 12:29 UTC
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  RHEL7/8 /CENTOS7/8 OL7/8
Perl version : n/a

### OCS Inventory informations
Unix agent version : 2.9.3

### Problem's description
ssl=0 is not respected with a 'https' site. see  #336. why was this closed without resolution?"

### Inventory log file ( optional )
N/A

**Comment by charleneauger** [comment] 2023-03-28 08:07
Hi @Sloth-on-meth ,

I can't reproduce the problem.
My agent configuration is as follows:

```
snmptimeout=3
debug=1
snmpretry=2
snmp=
tag=MYSQL-SERVER
nosoftware=0
server=https://ocs-test/ocsinventory
ssl=0
logfile=/var/log/ocsng.log
basevardir=/var/lib/ocsinventory-agent
```

And the inventory sends correctly.
I specify that my tests are carried out with a 2.10.0 agent.

Can you try with the latest version ?

Best regards,
Charlene

**Comment by charleneauger** [comment] 2023-05-22 12:26
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene

**Closed by charleneauger** 2023-05-22 12:26 UTC
