### ISSUE TITLE
500 Internal Server Error with some unix agents

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/UnixAgent#54] opened 2017-01-27 08:40 UTC
Hey,

now with two unix agent i get the error above. But what i read out of the logs communication works.
Server activity.log:
```
Fri Jan 27 09:18:23 2017;3424;103;ittst-nb096-2017-01-27-09-07-31;10.40.10.73;OCS-NG_unified_unix_agent_v2.3;prolog;new_deviceid
Fri Jan 27 09:18:23 2017;3424;104;ittst-nb096-2017-01-27-09-07-31;10.40.10.73;OCS-NG_unified_unix_agent_v2.3;snmp;error: agent must have a deviceid in database !!
Fri Jan 27 09:18:23 2017;3424;100;ittst-nb096-2017-01-27-09-07-31;10.40.10.73;OCS-NG_unified_unix_agent_v2.3;prolog;accepted
Fri Jan 27 09:18:23 2017;3424;311;ittst-nb096-2017-01-27-09-07-31;10.40.10.73;OCS-NG_unified_unix_agent_v2.3;session;started
Fri Jan 27 09:18:25 2017;3424;319;ittst-nb096-2017-01-27-09-07-31;10.40.10.73;OCS-NG_unified_unix_agent_v2.3;session;found
Fri Jan 27 09:18:25 2017;3424;104;ittst-nb096-2017-01-27-09-07-31;10.40.10.73;OCS-NG_unified_unix_agent_v2.3;inventory;incoming
Fri Jan 27 09:18:25 2017;3424;528;ittst-nb096-2017-01-27-09-07-31;10.40.10.73;OCS-NG_unified_unix_agent_v2.3;accountinfos;missing
```
Apache error.log:
```
[Fri Jan 27 09:18:25.592592 2017] [perl:error] [pid 3424] [client 10.40.10.73:41836] Not a HASH reference at /usr/local/share/perl/5.22.1/Apache/Ocsinventory/Server/Inventory/Data.pm line 126.\n
```
Agent log (not debug but i can also post it if you want):
`[Fri Jan 27 09:18:25 2017][error] Cannot establish communication : 500 Internal Server Error`

We use OCS Server and client 2.3 , also client and server are both Ubuntu 16.04.
We also have working unix clients also with OCS Agent 2,3 and Ubuntu 16.04

```
Fri Jan 27 09:39:51 2017;31625;100;rmvm052-2017-01-24-09-38-38;10.10.2.53;OCS-NG_unified_unix_agent_v2.3;prolog;accepted
Fri Jan 27 09:39:51 2017;31625;311;rmvm052-2017-01-24-09-38-38;10.10.2.53;OCS-NG_unified_unix_agent_v2.3;session;started
Fri Jan 27 09:39:53 2017;31625;319;rmvm052-2017-01-24-09-38-38;10.10.2.53;OCS-NG_unified_unix_agent_v2.3;session;found
Fri Jan 27 09:39:53 2017;31625;104;rmvm052-2017-01-24-09-38-38;10.10.2.53;OCS-NG_unified_unix_agent_v2.3;inventory;incoming
Fri Jan 27 09:39:53 2017;31625;113;rmvm052-2017-01-24-09-38-38;10.10.2.53;OCS-NG_unified_unix_agent_v2.3;inventory;u:drives
Fri Jan 27 09:39:53 2017;31625;320;rmvm052-2017-01-24-09-38-38;10.10.2.53;OCS-NG_unified_unix_agent_v2.3;session;end
Fri Jan 27 09:39:53 2017;31625;101;rmvm052-2017-01-24-09-38-38;10.10.2.53;OCS-NG_unified_unix_agent_v2.3;inventory;transmitted
```

Any ideas what went wrong? You need any other information?

**Comment by StCyr** [comment] 2017-01-31 07:55
Hello,

this is same as https://github.com/OCSInventory-NG/OCSInventory-Server/issues/40

We could work around the problem by removing the Ocsinventory/Agent/Backend/OS/Generic/Lsusb.pm file on the impacted agent.

Though, I think the problem is more on the server-side since the inventory reported by the agent looks correct, even when the lsusb.pm file is present.

Cyrille

**Comment by scifire91** [comment] 2017-01-31 09:47
If i delete /usr/local/share/perl/5.22.1/Ocsinventory/Agent/Backend/OS/Generic/Lsusb.pm
Nothing changes. Inventory is still not possible

**Comment by StCyr** [comment] 2017-01-31 09:52
Funny :-)

Can you change the file data.pm on the server as explained in my issue?

This way you're able to see what part of the inventory breaks your server. maybe there's another faulty module than lsusb...

**Comment by scifire91** [comment] 2017-02-01 10:17
@StCyr i can do it if you translate it what you´ve changed ;-)

**Comment by StCyr** [comment] 2017-02-01 10:40
Hello,

I added the following lines (ie: those prepended by a "+" sign) to the Data.pm file:

```
sub _get_bind_values{
  my ($refXml, $sectionMeta, $arrayToFeed) = @_;

  my ($bind_value, $xmlvalue, $xmlfield);

+#CBU
+if (ref($refXml) eq "ARRAY")
+{
+  print STDERR "refXml:\n";
+  for (@$refXml)
+  {
+      print STDERR Dumper($_);
+  }
+} else
+{
+  print STDERR "refXml: $refXml\n";
+}
+#CBU

  for my $field ( @{ $sectionMeta->{field_arrayref} } ) {
+    print STDERR "field = $field - refXml->field = $refXml->{$field}\n"; # CBU
    if(defined($refXml->{$field}) && !defined($sectionMeta->{fields}->{$field}->{type}) && $refXml->{$field} ne '' && $refXml->{$field} ne '??' && $refXml->{$field}!~/^N\/?A$/) {
      $bind_value = $refXml->{$field}
    }
    else{
       if( defined $sectionMeta->{fields}->{$field}->{fallback} ){
         $bind_value = $sectionMeta->{fields}->{$field}->{fallback};
         &_log( 000, 'fallback', "$field:".$sectionMeta->{fields}->{$field}->{fallback}) if $ENV{'OCS_OPT_LOGLEVEL'}>1;
       }
       else{
         &_log( 000, 'generic-fallback', "$field:".$sectionMeta->{fields}->{$field}->{fallback}) if $ENV{'OCS_OPT_LOGLEVEL'}>1;
         $bind_value = '';
       }
    }
```

You also need to add a `use Data::Dumper;` statementat the beginning of the file for this be functional.

After that, you can look at your Apache's error log file to have more clue where it fails.

Additionaly, it seems that there's also quite a big issue with a missing table in the OCS database. Maybe adding it by hand can also help:

```
CREATE TABLE usbdevices (
    `ID` int(11) not null AUTO_INCREMENT,
    `HARDWARE_ID` int(11)  NOT NULL,
    `TYPE` varchar(255) DEFAULT NULL,
    `MANUFACTURER` varchar(255) default null,
    `SERIAL` varchar(255) default null,
    `INTERFACE` varchar(255) DEFAULT NULL,
    `DESCRIPTION` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`ID`,`HARDWARE_ID`),
    key `MANUFACTURER` (`MANUFACTURER`)
 ) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
```

Regards,

Cyrille

**Comment by scifire91** [comment] 2017-02-01 15:01
Thanks for that :) 
Now i have extended log
apache error log from the first device:
```
refXml: HASH(0x55b5a2f88868)
field = SPEED - refXml->field = 1600
field = SERIALNUMBER - refXml->field = 21128414
field = CAPACITY - refXml->field = 8192
field = DESCRIPTION - refXml->field = Synchronous
field = PURPOSE - refXml->field =
field = CAPTION - refXml->field = ChannelA-DIMM0
field = NUMSLOTS - refXml->field =
field = TYPE - refXml->field = DDR3
refXml: HASH(0x55b5a2f3d858)
field = BVERSION - refXml->field = N10ET36W (1.15 )
field = TYPE - refXml->field = Notebook
field = SMODEL - refXml->field = 20CMCTO1WW
field = ASSETTAG - refXml->field = No Asset Information
field = BMANUFACTURER - refXml->field = LENOVO
field = SSN - refXml->field = PC0AHUC9
field = SMANUFACTURER - refXml->field = LENOVO
field = BDATE - refXml->field = 06/19/2015
refXml:
$VAR1 = {
          'MANUFACTURER' => 'SANYO',
          'SBDSVERSION' => '03.01',
          'OEMSPECIFIC' => '0x00000000',
          'DESIGNCAPACITY' => '23200 mWh',
          'DESIGNVOLTAGE' => '11100 mV',
          'MAXERROR' => 'Unknown',
          'NAME' => '45N1773',
          'LOCATION' => 'Front'
        };
$VAR1 = {
          'SBDSVERSION' => '03.01',
          'MANUFACTURER' => 'LGC',
          'MAXERROR' => 'Unknown',
          'DESIGNVOLTAGE' => '11220 mV',
          'DESIGNCAPACITY' => '71100 mWh',
          'OEMSPECIFIC' => '0x00000000',
          'NAME' => '45N1738',
          'LOCATION' => 'Rear'
        };
[Wed Feb 01 15:36:59.817621 2017] [perl:error] [pid 5741] [client 10.40.10.73:44380] Not a HASH reference at /usr/local/share/perl/5.22.1/Apache/Ocsinventory/Server/Inventory/Data.pm line 145.\n

```
error log from the other host is much longer so i pasted in into pastebin
http://pastebin.com/2KiRySC6

what i could read out of the log is that the first device has problems with battery and the second one with usb hubs?

**Comment by StCyr** [comment] 2017-02-01 15:48
As far as I understand, the problem comes from bad processing of the inventory by the server.

The error logs you have now help you identifying on what part of the inventory the server chokes. For what I'm concerned, the part of the inventory was the "USBDVICES" section.

Now, I don't know how to fix that error, and don't have much resources to investigate more, but, if you're also concerned with the "USBDEVICES" section, adding the `usbdevices` table as described above may help you.

I can't help you more atm sorry,

Cyrille

**Comment by scifire91** [comment] 2017-02-02 09:39
i´ve added the table usbdevicec from above but it´s still doesn´t work. Now i have also an completely different report in the apache error log.
Anyway thanks for your hints, maybe some from the team can investigate it.

**Comment by fbomj** [comment] 2017-02-10 15:10
This is not a bug in unix agent but this will be fixed in ocsinventory server project.

Regards
Frank

**Closed by fbomj** 2017-02-10 15:10 UTC
Labels: wontfix

**Comment by scifire91** [comment] 2017-02-10 15:27
@fbomj can you please reference the bug on the server project.

**Comment by gillesdubois** [comment] 2017-02-10 16:42
Take a look at : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/8debb5318702b9adc91a0a5df6cf4a7a7ba6d92e
